[package]
name = "rbxrootx/react-fluid"
description = "Persistent motion, continuous paths and overlapping reveals for React-Lua"
version = "0.6.0"
private = true
authors = ["Jack Fox <jack@infernal.io>"]
homepage = "https://github.com/rbxrootx/react-fluid"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/rbxrootx/react-fluid"
realm = "shared"

[dependencies]
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
Promise = "evaera/promise@4.0.0"
